name: snappy-hello # the name of the snap
version: 0.1 # the version of the snap
summary: Snappy Hello Demo # 79 char long summary
description: This is a demo of snappy package # A longer description for the snap
icon: icon.png # A path to an icon for the package

apps:
    snappy-hello:
        command: usr/bin/python $SNAP/bin/snappy-hello

parts:
    snappy-hello:
        plugin: python2
        source: .
        build-packages: [gcc, python-dev, libc6-dev]
    make-project:
        plugin: make
        source: .
